package dev.com.matricula.model;

// Generated 27/04/2014 12:29:47 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AsignacionDTO generated by hbm2java
 */
public class Asignacion implements java.io.Serializable {

  private Integer idAsignacion;
  private Docente docente;
  private Curso curso;
  private AnhoEscolar anhoEscolar;
  private short horasTeoricas;
  private short horasPracticas;
  private String nivel;
  private String grado;
  private char seccion;
  private String usuarioInscripcion;
  private Date fechaInscripcion;
  private String usuarioModificacion;
  private Date fechaModificacion;
  private Set notases = new HashSet(0);
  private Set horarios = new HashSet(0);

  public Asignacion() {
  }

  public Asignacion(Docente docente, Curso curso, AnhoEscolar anhoEscolar, short horasTeoricas,
          short horasPracticas, String nivel, String grado, char seccion) {
    this.docente = docente;
    this.curso = curso;
    this.anhoEscolar = anhoEscolar;
    this.horasTeoricas = horasTeoricas;
    this.horasPracticas = horasPracticas;
    this.nivel = nivel;
    this.grado = grado;
    this.seccion = seccion;
  }

  public Asignacion(Docente docente, Curso curso, AnhoEscolar anhoEscolar, short horasTeoricas,
          short horasPracticas, String nivel, String grado, char seccion,
          String usuarioInscripcion, Date fechaInscripcion, String usuarioModificacion,
          Date fechaModificacion, Set notases, Set horarios) {
    this.docente = docente;
    this.curso = curso;
    this.anhoEscolar = anhoEscolar;
    this.horasTeoricas = horasTeoricas;
    this.horasPracticas = horasPracticas;
    this.nivel = nivel;
    this.grado = grado;
    this.seccion = seccion;
    this.usuarioInscripcion = usuarioInscripcion;
    this.fechaInscripcion = fechaInscripcion;
    this.usuarioModificacion = usuarioModificacion;
    this.fechaModificacion = fechaModificacion;
    this.notases = notases;
    this.horarios = horarios;
  }

  public Integer getIdAsignacion() {
    return this.idAsignacion;
  }

  public void setIdAsignacion(Integer idAsignacion) {
    this.idAsignacion = idAsignacion;
  }

  public Docente getDocente() {
    return this.docente;
  }

  public void setDocente(Docente docente) {
    this.docente = docente;
  }

  public Curso getCurso() {
    return this.curso;
  }

  public void setCurso(Curso curso) {
    this.curso = curso;
  }

  public AnhoEscolar getAnhoEscolar() {
    return this.anhoEscolar;
  }

  public void setAnhoEscolar(AnhoEscolar anhoEscolar) {
    this.anhoEscolar = anhoEscolar;
  }

  public short getHorasTeoricas() {
    return this.horasTeoricas;
  }

  public void setHorasTeoricas(short horasTeoricas) {
    this.horasTeoricas = horasTeoricas;
  }

  public short getHorasPracticas() {
    return this.horasPracticas;
  }

  public void setHorasPracticas(short horasPracticas) {
    this.horasPracticas = horasPracticas;
  }

  public String getNivel() {
    return this.nivel;
  }

  public void setNivel(String nivel) {
    this.nivel = nivel;
  }

  public String getGrado() {
    return this.grado;
  }

  public void setGrado(String grado) {
    this.grado = grado;
  }

  public char getSeccion() {
    return this.seccion;
  }

  public void setSeccion(char seccion) {
    this.seccion = seccion;
  }

  public String getUsuarioInscripcion() {
    return this.usuarioInscripcion;
  }

  public void setUsuarioInscripcion(String usuarioInscripcion) {
    this.usuarioInscripcion = usuarioInscripcion;
  }

  public Date getFechaInscripcion() {
    return this.fechaInscripcion;
  }

  public void setFechaInscripcion(Date fechaInscripcion) {
    this.fechaInscripcion = fechaInscripcion;
  }

  public String getUsuarioModificacion() {
    return this.usuarioModificacion;
  }

  public void setUsuarioModificacion(String usuarioModificacion) {
    this.usuarioModificacion = usuarioModificacion;
  }

  public Date getFechaModificacion() {
    return this.fechaModificacion;
  }

  public void setFechaModificacion(Date fechaModificacion) {
    this.fechaModificacion = fechaModificacion;
  }

  public Set getNotases() {
    return this.notases;
  }

  public void setNotases(Set notases) {
    this.notases = notases;
  }

  public Set getHorarios() {
    return this.horarios;
  }

  public void setHorarios(Set horarios) {
    this.horarios = horarios;
  }

}
