package dev.com.matricula.model;

// Generated 27/04/2014 12:29:47 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso implements java.io.Serializable {

  private Integer idCurso;
  private String descripcion;
  private String usuarioInscripcion;
  private Date fechaInscripcion;
  private Set asignacions = new HashSet(0);

  public Curso() {
  }

  public Curso(String descripcion) {
    this.descripcion = descripcion;
  }

  public Curso(String descripcion, String usuarioInscripcion, Date fechaInscripcion, Set asignacions) {
    this.descripcion = descripcion;
    this.usuarioInscripcion = usuarioInscripcion;
    this.fechaInscripcion = fechaInscripcion;
    this.asignacions = asignacions;
  }

  public Integer getIdCurso() {
    return this.idCurso;
  }

  public void setIdCurso(Integer idCurso) {
    this.idCurso = idCurso;
  }

  public String getDescripcion() {
    return this.descripcion;
  }

  public void setDescripcion(String descripcion) {
    this.descripcion = descripcion;
  }

  public String getUsuarioInscripcion() {
    return this.usuarioInscripcion;
  }

  public void setUsuarioInscripcion(String usuarioInscripcion) {
    this.usuarioInscripcion = usuarioInscripcion;
  }

  public Date getFechaInscripcion() {
    return this.fechaInscripcion;
  }

  public void setFechaInscripcion(Date fechaInscripcion) {
    this.fechaInscripcion = fechaInscripcion;
  }

  public Set getAsignacions() {
    return this.asignacions;
  }

  public void setAsignacions(Set asignacions) {
    this.asignacions = asignacions;
  }

}
