package dev.com.matricula.model;

// Generated 27/04/2014 12:29:47 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Horario generated by hbm2java
 */
public class Horario implements java.io.Serializable {

  private Integer idHorario;
  private Aula aula;
  private Asignacion asignacion;
  private String dia;
  private Date horaInicial;
  private Date horaFinal;
  private String usuarioInscripcion;
  private Date fechaInscripcion;
  private String usuarioModificacion;
  private Date fechaModificacion;

  public Horario() {
  }

  public Horario(Aula aula, Asignacion asignacion, String dia, Date horaInicial, Date horaFinal) {
    this.aula = aula;
    this.asignacion = asignacion;
    this.dia = dia;
    this.horaInicial = horaInicial;
    this.horaFinal = horaFinal;
  }

  public Horario(Aula aula, Asignacion asignacion, String dia, Date horaInicial, Date horaFinal,
          String usuarioInscripcion, Date fechaInscripcion, String usuarioModificacion,
          Date fechaModificacion) {
    this.aula = aula;
    this.asignacion = asignacion;
    this.dia = dia;
    this.horaInicial = horaInicial;
    this.horaFinal = horaFinal;
    this.usuarioInscripcion = usuarioInscripcion;
    this.fechaInscripcion = fechaInscripcion;
    this.usuarioModificacion = usuarioModificacion;
    this.fechaModificacion = fechaModificacion;
  }

  public Integer getIdHorario() {
    return this.idHorario;
  }

  public void setIdHorario(Integer idHorario) {
    this.idHorario = idHorario;
  }

  public Aula getAula() {
    return this.aula;
  }

  public void setAula(Aula aula) {
    this.aula = aula;
  }

  public Asignacion getAsignacion() {
    return this.asignacion;
  }

  public void setAsignacion(Asignacion asignacion) {
    this.asignacion = asignacion;
  }

  public String getDia() {
    return this.dia;
  }

  public void setDia(String dia) {
    this.dia = dia;
  }

  public Date getHoraInicial() {
    return this.horaInicial;
  }

  public void setHoraInicial(Date horaInicial) {
    this.horaInicial = horaInicial;
  }

  public Date getHoraFinal() {
    return this.horaFinal;
  }

  public void setHoraFinal(Date horaFinal) {
    this.horaFinal = horaFinal;
  }

  public String getUsuarioInscripcion() {
    return this.usuarioInscripcion;
  }

  public void setUsuarioInscripcion(String usuarioInscripcion) {
    this.usuarioInscripcion = usuarioInscripcion;
  }

  public Date getFechaInscripcion() {
    return this.fechaInscripcion;
  }

  public void setFechaInscripcion(Date fechaInscripcion) {
    this.fechaInscripcion = fechaInscripcion;
  }

  public String getUsuarioModificacion() {
    return this.usuarioModificacion;
  }

  public void setUsuarioModificacion(String usuarioModificacion) {
    this.usuarioModificacion = usuarioModificacion;
  }

  public Date getFechaModificacion() {
    return this.fechaModificacion;
  }

  public void setFechaModificacion(Date fechaModificacion) {
    this.fechaModificacion = fechaModificacion;
  }

}
