package dev.com.matricula.model;

// Generated 27/04/2014 12:29:47 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * MatriculaDTO generated by hbm2java
 */
public class Matricula implements java.io.Serializable {

  private Integer idMatricula;
  private Colegio colegio;
  private Alumno alumno;
  private Apoderado apoderado;
  private AnhoEscolar anhoEscolar;
  private Date fechaMatricula;
  private String nivel;
  private String grado;
  private char seccion;
  private char turno;
  private String situacion;
  private char estado;
  private String observacion;
  private String usuarioInscripcion;
  private Date fechaInscripcion;

  public Matricula() {
  }

  public Matricula(Colegio colegio, Alumno alumno, Apoderado apoderado, AnhoEscolar anhoEscolar,
          Date fechaMatricula, String nivel, String grado, char seccion, char turno, char estado) {
    this.colegio = colegio;
    this.alumno = alumno;
    this.apoderado = apoderado;
    this.anhoEscolar = anhoEscolar;
    this.fechaMatricula = fechaMatricula;
    this.nivel = nivel;
    this.grado = grado;
    this.seccion = seccion;
    this.turno = turno;
    this.estado = estado;
  }

  public Matricula(Colegio colegio, Alumno alumno, Apoderado apoderado, AnhoEscolar anhoEscolar,
          Date fechaMatricula, String nivel, String grado, char seccion, char turno,
          String situacion, char estado, String observacion, String usuarioInscripcion,
          Date fechaInscripcion) {
    this.colegio = colegio;
    this.alumno = alumno;
    this.apoderado = apoderado;
    this.anhoEscolar = anhoEscolar;
    this.fechaMatricula = fechaMatricula;
    this.nivel = nivel;
    this.grado = grado;
    this.seccion = seccion;
    this.turno = turno;
    this.situacion = situacion;
    this.estado = estado;
    this.observacion = observacion;
    this.usuarioInscripcion = usuarioInscripcion;
    this.fechaInscripcion = fechaInscripcion;
  }

  public Integer getIdMatricula() {
    return this.idMatricula;
  }

  public void setIdMatricula(Integer idMatricula) {
    this.idMatricula = idMatricula;
  }

  public Colegio getColegio() {
    return this.colegio;
  }

  public void setColegio(Colegio colegio) {
    this.colegio = colegio;
  }

  public Alumno getAlumno() {
    return this.alumno;
  }

  public void setAlumno(Alumno alumno) {
    this.alumno = alumno;
  }

  public Apoderado getApoderado() {
    return this.apoderado;
  }

  public void setApoderado(Apoderado apoderado) {
    this.apoderado = apoderado;
  }

  public AnhoEscolar getAnhoEscolar() {
    return this.anhoEscolar;
  }

  public void setAnhoEscolar(AnhoEscolar anhoEscolar) {
    this.anhoEscolar = anhoEscolar;
  }

  public Date getFechaMatricula() {
    return this.fechaMatricula;
  }

  public void setFechaMatricula(Date fechaMatricula) {
    this.fechaMatricula = fechaMatricula;
  }

  public String getNivel() {
    return this.nivel;
  }

  public void setNivel(String nivel) {
    this.nivel = nivel;
  }

  public String getGrado() {
    return this.grado;
  }

  public void setGrado(String grado) {
    this.grado = grado;
  }

  public char getSeccion() {
    return this.seccion;
  }

  public void setSeccion(char seccion) {
    this.seccion = seccion;
  }

  public char getTurno() {
    return this.turno;
  }

  public void setTurno(char turno) {
    this.turno = turno;
  }

  public String getSituacion() {
    return this.situacion;
  }

  public void setSituacion(String situacion) {
    this.situacion = situacion;
  }

  public char getEstado() {
    return this.estado;
  }

  public void setEstado(char estado) {
    this.estado = estado;
  }

  public String getObservacion() {
    return this.observacion;
  }

  public void setObservacion(String observacion) {
    this.observacion = observacion;
  }

  public String getUsuarioInscripcion() {
    return this.usuarioInscripcion;
  }

  public void setUsuarioInscripcion(String usuarioInscripcion) {
    this.usuarioInscripcion = usuarioInscripcion;
  }

  public Date getFechaInscripcion() {
    return this.fechaInscripcion;
  }

  public void setFechaInscripcion(Date fechaInscripcion) {
    this.fechaInscripcion = fechaInscripcion;
  }

}
