package dev.com.matricula.model;

// Generated 27/04/2014 12:29:47 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Parentesco generated by hbm2java
 */
public class Parentesco implements java.io.Serializable {

  private Integer idParentesco;
  private Alumno alumno;
  private Apoderado apoderado;
  private String parentesco;
  private String usuarioInscripcion;
  private Date fechaInscripcion;

  public Parentesco() {
  }

  public Parentesco(Alumno alumno, Apoderado apoderado, String parentesco) {
    this.alumno = alumno;
    this.apoderado = apoderado;
    this.parentesco = parentesco;
  }

  public Parentesco(Alumno alumno, Apoderado apoderado, String parentesco,
          String usuarioInscripcion, Date fechaInscripcion) {
    this.alumno = alumno;
    this.apoderado = apoderado;
    this.parentesco = parentesco;
    this.usuarioInscripcion = usuarioInscripcion;
    this.fechaInscripcion = fechaInscripcion;
  }

  public Integer getIdParentesco() {
    return this.idParentesco;
  }

  public void setIdParentesco(Integer idParentesco) {
    this.idParentesco = idParentesco;
  }

  public Alumno getAlumno() {
    return this.alumno;
  }

  public void setAlumno(Alumno alumno) {
    this.alumno = alumno;
  }

  public Apoderado getApoderado() {
    return this.apoderado;
  }

  public void setApoderado(Apoderado apoderado) {
    this.apoderado = apoderado;
  }

  public String getParentesco() {
    return this.parentesco;
  }

  public void setParentesco(String parentesco) {
    this.parentesco = parentesco;
  }

  public String getUsuarioInscripcion() {
    return this.usuarioInscripcion;
  }

  public void setUsuarioInscripcion(String usuarioInscripcion) {
    this.usuarioInscripcion = usuarioInscripcion;
  }

  public Date getFechaInscripcion() {
    return this.fechaInscripcion;
  }

  public void setFechaInscripcion(Date fechaInscripcion) {
    this.fechaInscripcion = fechaInscripcion;
  }

}
