package dev.com.matricula.model;

// Generated 27/04/2014 12:29:47 AM by Hibernate Tools 4.0.0

/**
 * Seccion generated by hbm2java
 */
public class Seccion implements java.io.Serializable {

  private char idSeccion;
  private String descripcion;

  public Seccion() {
  }

  public Seccion(char idSeccion) {
    this.idSeccion = idSeccion;
  }

  public Seccion(char idSeccion, String descripcion) {
    this.idSeccion = idSeccion;
    this.descripcion = descripcion;
  }

  public char getIdSeccion() {
    return this.idSeccion;
  }

  public void setIdSeccion(char idSeccion) {
    this.idSeccion = idSeccion;
  }

  public String getDescripcion() {
    return this.descripcion;
  }

  public void setDescripcion(String descripcion) {
    this.descripcion = descripcion;
  }

}
