package dev.com.matricula.model;

// Generated 27/04/2014 12:29:47 AM by Hibernate Tools 4.0.0

/**
 * UsuarioDocente generated by hbm2java
 */
public class UsuarioDocente implements java.io.Serializable {
  /**
   * 
   */
  private Integer idUsuarioDocente;
  private Docente docente;
  private Usuario usuario;
  private Character estado;

  public UsuarioDocente() {
  }

  public UsuarioDocente(Docente docente, Usuario usuario) {
    this.docente = docente;
    this.usuario = usuario;
  }

  public UsuarioDocente(Docente docente, Usuario usuario, Character estado) {
    this.docente = docente;
    this.usuario = usuario;
    this.estado = estado;
  }

  public Integer getIdUsuarioDocente() {
    return this.idUsuarioDocente;
  }

  public void setIdUsuarioDocente(Integer idUsuarioDocente) {
    this.idUsuarioDocente = idUsuarioDocente;
  }

  public Docente getDocente() {
    return this.docente;
  }

  public void setDocente(Docente docente) {
    this.docente = docente;
  }

  public Usuario getUsuario() {
    return this.usuario;
  }

  public void setUsuario(Usuario usuario) {
    this.usuario = usuario;
  }

  public Character getEstado() {
    return this.estado;
  }

  public void setEstado(Character estado) {
    this.estado = estado;
  }

}
