package dev.com.matricula.model;

// Generated 27/04/2014 12:29:47 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AnhoEscolar generated by hbm2java
 */
public class AnhoEscolar implements java.io.Serializable {

  private String idAnhoEscolar;
  private Date fechaInicial;
  private Date fechaFinal;
  private char estado;
  private String usuarioInscripcion;
  private Date fechaInscripcion;
  private Set matriculas = new HashSet(0);
  private Set asignacions = new HashSet(0);

  public AnhoEscolar() {
  }

  public AnhoEscolar(String idAnhoEscolar, Date fechaInicial, Date fechaFinal, char estado) {
    this.idAnhoEscolar = idAnhoEscolar;
    this.fechaInicial = fechaInicial;
    this.fechaFinal = fechaFinal;
    this.estado = estado;
  }

  public AnhoEscolar(String idAnhoEscolar, Date fechaInicial, Date fechaFinal, char estado,
          String usuarioInscripcion, Date fechaInscripcion, Set matriculas, Set asignacions) {
    this.idAnhoEscolar = idAnhoEscolar;
    this.fechaInicial = fechaInicial;
    this.fechaFinal = fechaFinal;
    this.estado = estado;
    this.usuarioInscripcion = usuarioInscripcion;
    this.fechaInscripcion = fechaInscripcion;
    this.matriculas = matriculas;
    this.asignacions = asignacions;
  }

  public String getIdAnhoEscolar() {
    return this.idAnhoEscolar;
  }

  public void setIdAnhoEscolar(String idAnhoEscolar) {
    this.idAnhoEscolar = idAnhoEscolar;
  }

  public Date getFechaInicial() {
    return this.fechaInicial;
  }

  public void setFechaInicial(Date fechaInicial) {
    this.fechaInicial = fechaInicial;
  }

  public Date getFechaFinal() {
    return this.fechaFinal;
  }

  public void setFechaFinal(Date fechaFinal) {
    this.fechaFinal = fechaFinal;
  }

  public char getEstado() {
    return this.estado;
  }

  public void setEstado(char estado) {
    this.estado = estado;
  }

  public String getUsuarioInscripcion() {
    return this.usuarioInscripcion;
  }

  public void setUsuarioInscripcion(String usuarioInscripcion) {
    this.usuarioInscripcion = usuarioInscripcion;
  }

  public Date getFechaInscripcion() {
    return this.fechaInscripcion;
  }

  public void setFechaInscripcion(Date fechaInscripcion) {
    this.fechaInscripcion = fechaInscripcion;
  }

  public Set getMatriculas() {
    return this.matriculas;
  }

  public void setMatriculas(Set matriculas) {
    this.matriculas = matriculas;
  }

  public Set getAsignacions() {
    return this.asignacions;
  }

  public void setAsignacions(Set asignacions) {
    this.asignacions = asignacions;
  }

}
