package dev.com.matricula.model;

// Generated 27/04/2014 12:29:47 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Apoderado generated by hbm2java
 */
public class Apoderado implements java.io.Serializable {

  private Integer idApoderado;
  private String nombre;
  private String apellidoPaterno;
  private String apellidoMaterno;
  private char sexo;
  private String dni;
  private String direccion;
  private Character estadoCivil;
  private String telefono;
  private String usuarioInscripcion;
  private Date fechaInscripcion;
  private Set matriculas = new HashSet(0);
  private Set parentescos = new HashSet(0);

  public Apoderado() {
  }

  public Apoderado(String nombre, String apellidoPaterno, String apellidoMaterno, char sexo,
          String dni) {
    this.nombre = nombre;
    this.apellidoPaterno = apellidoPaterno;
    this.apellidoMaterno = apellidoMaterno;
    this.sexo = sexo;
    this.dni = dni;
  }

  public Apoderado(String nombre, String apellidoPaterno, String apellidoMaterno, char sexo,
          String dni, String direccion, Character estadoCivil, String telefono,
          String usuarioInscripcion, Date fechaInscripcion, Set matriculas, Set parentescos) {
    this.nombre = nombre;
    this.apellidoPaterno = apellidoPaterno;
    this.apellidoMaterno = apellidoMaterno;
    this.sexo = sexo;
    this.dni = dni;
    this.direccion = direccion;
    this.estadoCivil = estadoCivil;
    this.telefono = telefono;
    this.usuarioInscripcion = usuarioInscripcion;
    this.fechaInscripcion = fechaInscripcion;
    this.matriculas = matriculas;
    this.parentescos = parentescos;
  }

  public Integer getIdApoderado() {
    return this.idApoderado;
  }

  public void setIdApoderado(Integer idApoderado) {
    this.idApoderado = idApoderado;
  }

  public String getNombre() {
    return this.nombre;
  }

  public void setNombre(String nombre) {
    this.nombre = nombre;
  }

  public String getApellidoPaterno() {
    return this.apellidoPaterno;
  }

  public void setApellidoPaterno(String apellidoPaterno) {
    this.apellidoPaterno = apellidoPaterno;
  }

  public String getApellidoMaterno() {
    return this.apellidoMaterno;
  }

  public void setApellidoMaterno(String apellidoMaterno) {
    this.apellidoMaterno = apellidoMaterno;
  }

  public char getSexo() {
    return this.sexo;
  }

  public void setSexo(char sexo) {
    this.sexo = sexo;
  }

  public String getDni() {
    return this.dni;
  }

  public void setDni(String dni) {
    this.dni = dni;
  }

  public String getDireccion() {
    return this.direccion;
  }

  public void setDireccion(String direccion) {
    this.direccion = direccion;
  }

  public Character getEstadoCivil() {
    return this.estadoCivil;
  }

  public void setEstadoCivil(Character estadoCivil) {
    this.estadoCivil = estadoCivil;
  }

  public String getTelefono() {
    return this.telefono;
  }

  public void setTelefono(String telefono) {
    this.telefono = telefono;
  }

  public String getUsuarioInscripcion() {
    return this.usuarioInscripcion;
  }

  public void setUsuarioInscripcion(String usuarioInscripcion) {
    this.usuarioInscripcion = usuarioInscripcion;
  }

  public Date getFechaInscripcion() {
    return this.fechaInscripcion;
  }

  public void setFechaInscripcion(Date fechaInscripcion) {
    this.fechaInscripcion = fechaInscripcion;
  }

  public Set getMatriculas() {
    return this.matriculas;
  }

  public void setMatriculas(Set matriculas) {
    this.matriculas = matriculas;
  }

  public Set getParentescos() {
    return this.parentescos;
  }

  public void setParentescos(Set parentescos) {
    this.parentescos = parentescos;
  }

}
