package dev.com.matricula.model;

// Generated 27/04/2014 12:29:47 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Aula generated by hbm2java
 */
public class Aula implements java.io.Serializable {

  private Integer idAula;
  private String tipo;
  private short capacidad;
  private Set horarios = new HashSet(0);

  public Aula() {
  }

  public Aula(String tipo, short capacidad) {
    this.tipo = tipo;
    this.capacidad = capacidad;
  }

  public Aula(String tipo, short capacidad, Set horarios) {
    this.tipo = tipo;
    this.capacidad = capacidad;
    this.horarios = horarios;
  }

  public Integer getIdAula() {
    return this.idAula;
  }

  public void setIdAula(Integer idAula) {
    this.idAula = idAula;
  }

  public String getTipo() {
    return this.tipo;
  }

  public void setTipo(String tipo) {
    this.tipo = tipo;
  }

  public short getCapacidad() {
    return this.capacidad;
  }

  public void setCapacidad(short capacidad) {
    this.capacidad = capacidad;
  }

  public Set getHorarios() {
    return this.horarios;
  }

  public void setHorarios(Set horarios) {
    this.horarios = horarios;
  }

}
