package dev.com.matricula.model;

// Generated 27/04/2014 12:29:47 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Colegio generated by hbm2java
 */
public class Colegio implements java.io.Serializable {

  private Integer idColegio;
  private String nombre;
  private String direccion;
  private char tipo;
  private Set matriculas = new HashSet(0);

  public Colegio() {
  }

  public Colegio(String nombre, String direccion, char tipo) {
    this.nombre = nombre;
    this.direccion = direccion;
    this.tipo = tipo;
  }

  public Colegio(String nombre, String direccion, char tipo, Set matriculas) {
    this.nombre = nombre;
    this.direccion = direccion;
    this.tipo = tipo;
    this.matriculas = matriculas;
  }

  public Integer getIdColegio() {
    return this.idColegio;
  }

  public void setIdColegio(Integer idColegio) {
    this.idColegio = idColegio;
  }

  public String getNombre() {
    return this.nombre;
  }

  public void setNombre(String nombre) {
    this.nombre = nombre;
  }

  public String getDireccion() {
    return this.direccion;
  }

  public void setDireccion(String direccion) {
    this.direccion = direccion;
  }

  public char getTipo() {
    return this.tipo;
  }

  public void setTipo(char tipo) {
    this.tipo = tipo;
  }

  public Set getMatriculas() {
    return this.matriculas;
  }

  public void setMatriculas(Set matriculas) {
    this.matriculas = matriculas;
  }

}
