package dev.com.matricula.model;

// Generated 27/04/2014 12:29:47 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Docente generated by hbm2java
 */
public class Docente implements java.io.Serializable {

  private Integer idDocente;
  private String nombre;
  private String apellidoPaterno;
  private String apellidoMaterno;
  private String direccion;
  private String telefono;
  private String dni;
  private String especialidad;
  private String email;
  private char sexo;
  private String usuarioInscripcion;
  private Date fechaInscripcion;
  private Set asignacions = new HashSet(0);
  private Set usuariodocentes = new HashSet(0);

  public Docente() {
  }

  public Docente(String nombre, String apellidoPaterno, String apellidoMaterno, String dni,
          String especialidad, char sexo) {
    this.nombre = nombre;
    this.apellidoPaterno = apellidoPaterno;
    this.apellidoMaterno = apellidoMaterno;
    this.dni = dni;
    this.especialidad = especialidad;
    this.sexo = sexo;
  }

  public Docente(String nombre, String apellidoPaterno, String apellidoMaterno, String direccion,
          String telefono, String dni, String especialidad, String email, char sexo,
          String usuarioInscripcion, Date fechaInscripcion, Set asignacions, Set usuariodocentes) {
    this.nombre = nombre;
    this.apellidoPaterno = apellidoPaterno;
    this.apellidoMaterno = apellidoMaterno;
    this.direccion = direccion;
    this.telefono = telefono;
    this.dni = dni;
    this.especialidad = especialidad;
    this.email = email;
    this.sexo = sexo;
    this.usuarioInscripcion = usuarioInscripcion;
    this.fechaInscripcion = fechaInscripcion;
    this.asignacions = asignacions;
    this.usuariodocentes = usuariodocentes;
  }

  public Integer getIdDocente() {
    return this.idDocente;
  }

  public void setIdDocente(Integer idDocente) {
    this.idDocente = idDocente;
  }

  public String getNombre() {
    return this.nombre;
  }

  public void setNombre(String nombre) {
    this.nombre = nombre;
  }

  public String getApellidoPaterno() {
    return this.apellidoPaterno;
  }

  public void setApellidoPaterno(String apellidoPaterno) {
    this.apellidoPaterno = apellidoPaterno;
  }

  public String getApellidoMaterno() {
    return this.apellidoMaterno;
  }

  public void setApellidoMaterno(String apellidoMaterno) {
    this.apellidoMaterno = apellidoMaterno;
  }

  public String getDireccion() {
    return this.direccion;
  }

  public void setDireccion(String direccion) {
    this.direccion = direccion;
  }

  public String getTelefono() {
    return this.telefono;
  }

  public void setTelefono(String telefono) {
    this.telefono = telefono;
  }

  public String getDni() {
    return this.dni;
  }

  public void setDni(String dni) {
    this.dni = dni;
  }

  public String getEspecialidad() {
    return this.especialidad;
  }

  public void setEspecialidad(String especialidad) {
    this.especialidad = especialidad;
  }

  public String getEmail() {
    return this.email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public char getSexo() {
    return this.sexo;
  }

  public void setSexo(char sexo) {
    this.sexo = sexo;
  }

  public String getUsuarioInscripcion() {
    return this.usuarioInscripcion;
  }

  public void setUsuarioInscripcion(String usuarioInscripcion) {
    this.usuarioInscripcion = usuarioInscripcion;
  }

  public Date getFechaInscripcion() {
    return this.fechaInscripcion;
  }

  public void setFechaInscripcion(Date fechaInscripcion) {
    this.fechaInscripcion = fechaInscripcion;
  }

  public Set getAsignacions() {
    return this.asignacions;
  }

  public void setAsignacions(Set asignacions) {
    this.asignacions = asignacions;
  }

  public Set getUsuariodocentes() {
    return this.usuariodocentes;
  }

  public void setUsuariodocentes(Set usuariodocentes) {
    this.usuariodocentes = usuariodocentes;
  }

}
