package dev.com.matricula.model;

// Generated 27/04/2014 12:29:47 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol implements java.io.Serializable {

  private Integer idRol;
  private String descripcion;
  private char estado;
  private Set rolusuarios = new HashSet(0);

  public Rol() {
  }

  public Rol(String descripcion, char estado) {
    this.descripcion = descripcion;
    this.estado = estado;
  }

  public Rol(String descripcion, char estado, Set rolusuarios) {
    this.descripcion = descripcion;
    this.estado = estado;
    this.rolusuarios = rolusuarios;
  }

  public Integer getIdRol() {
    return this.idRol;
  }

  public void setIdRol(Integer idRol) {
    this.idRol = idRol;
  }

  public String getDescripcion() {
    return this.descripcion;
  }

  public void setDescripcion(String descripcion) {
    this.descripcion = descripcion;
  }

  public char getEstado() {
    return this.estado;
  }

  public void setEstado(char estado) {
    this.estado = estado;
  }

  public Set getRolusuarios() {
    return this.rolusuarios;
  }

  public void setRolusuarios(Set rolusuarios) {
    this.rolusuarios = rolusuarios;
  }

}
