package dev.com.matricula.model;

// Generated 27/04/2014 12:29:47 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

  private Integer idUsuario;
  private String nombre;
  private String dni;
  private String login;
  private String clave;
  private char estado;
  private String usuarioInscripcion;
  private Date fechaInscripcion;
  private Set rolusuarios = new HashSet(0);
  private Set usuariodocentes = new HashSet(0);
  private Set usuarioalumnos = new HashSet(0);

  public Usuario() {
  }

  public Usuario(String nombre, String dni, String login, String clave, char estado) {
    this.nombre = nombre;
    this.dni = dni;
    this.login = login;
    this.clave = clave;
    this.estado = estado;
  }

  public Usuario(String nombre, String dni, String login, String clave, char estado,
          String usuarioInscripcion, Date fechaInscripcion, Set rolusuarios, Set usuariodocentes,
          Set usuarioalumnos) {
    this.nombre = nombre;
    this.dni = dni;
    this.login = login;
    this.clave = clave;
    this.estado = estado;
    this.usuarioInscripcion = usuarioInscripcion;
    this.fechaInscripcion = fechaInscripcion;
    this.rolusuarios = rolusuarios;
    this.usuariodocentes = usuariodocentes;
    this.usuarioalumnos = usuarioalumnos;
  }

  public Integer getIdUsuario() {
    return this.idUsuario;
  }

  public void setIdUsuario(Integer idUsuario) {
    this.idUsuario = idUsuario;
  }

  public String getNombre() {
    return this.nombre;
  }

  public void setNombre(String nombre) {
    this.nombre = nombre;
  }

  public String getDni() {
    return this.dni;
  }

  public void setDni(String dni) {
    this.dni = dni;
  }

  public String getLogin() {
    return this.login;
  }

  public void setLogin(String login) {
    this.login = login;
  }

  public String getClave() {
    return this.clave;
  }

  public void setClave(String clave) {
    this.clave = clave;
  }

  public char getEstado() {
    return this.estado;
  }

  public void setEstado(char estado) {
    this.estado = estado;
  }

  public String getUsuarioInscripcion() {
    return this.usuarioInscripcion;
  }

  public void setUsuarioInscripcion(String usuarioInscripcion) {
    this.usuarioInscripcion = usuarioInscripcion;
  }

  public Date getFechaInscripcion() {
    return this.fechaInscripcion;
  }

  public void setFechaInscripcion(Date fechaInscripcion) {
    this.fechaInscripcion = fechaInscripcion;
  }

  public Set getRolusuarios() {
    return this.rolusuarios;
  }

  public void setRolusuarios(Set rolusuarios) {
    this.rolusuarios = rolusuarios;
  }

  public Set getUsuariodocentes() {
    return this.usuariodocentes;
  }

  public void setUsuariodocentes(Set usuariodocentes) {
    this.usuariodocentes = usuariodocentes;
  }

  public Set getUsuarioalumnos() {
    return this.usuarioalumnos;
  }

  public void setUsuarioalumnos(Set usuarioalumnos) {
    this.usuarioalumnos = usuarioalumnos;
  }

}
